[package]
name = "rgen3-save"
version = "0.1.0"
authors = ["Mika Attila <radiantstatue@gmail.com>"]

[dependencies]
log = "0.3"
byteorder = "0.5"

[dependencies.rgen3-string]
path = "../rgen3-string"

[dev-dependencies]
env_logger = "0.3"
rand = "0.3"
